# Standard-Profil für den Betrieb auf Produktion setzen
spring.profiles.active=prod

# Optionale externe Konfigurationsdatei für Sysadmins importieren (überschreibt Standardwerte)
spring.config.import=optional:file:./maintenance-tool.properties,optional:file:/etc/maintenance-tool/maintenance-tool.properties


# Anwendungs-Metadaten
spring.application.name=maintenance-tool

# Servlet & Server-Port
server.port=8080

# JPA/Hibernate: Open Session in View (OSIV) deaktivieren für bessere Performance und Ressourcenschonung
spring.jpa.open-in-view=false

# Virtuelle Threads (Project Loom) aktivieren für hocheffiziente Concurrent-Request-Verarbeitung
spring.threads.virtual.enabled=true

